using System;

namespace bgs
{
	public enum LeaveReason
	{
		MEMBER_LEFT,
		MEMBER_KICKED,
		DISSOLVED_BY_MEMBER,
		MEMBER_DISCONNECTED,
		MEMBER_REMOVED_BY_SERVICE,
		DISSOLVED_BY_SERVICE,
		DISCONNECTED,
		UNKNOWN,
		PLAYER_REMOVED_BY_GAME_SERVER,
		GAME_ENDED_BY_GAME_SERVER,
		PLAYER_DISCONNECTED_FROM_GAME_SERVER,
		GAME_SERVER_DISCONNECTED_FROM_SERVICE,
		CHANNEL_HOST_DISCONNECTED_FROM_SERVICE,
		GAME_MASTER_DISCONNECTED_FROM_SERVICE,
		FOUNDER_LEFT
	}
}
