using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_STATUS
	{
		CALENDAR_STATUS_INVITED,
		CALENDAR_STATUS_AVAILABLE,
		CALENDAR_STATUS_DECLINED,
		CALENDAR_STATUS_CONFIRMED,
		CALENDAR_STATUS_OUT,
		CALENDAR_STATUS_STANDBY,
		CALENDAR_STATUS_SIGNEDUP,
		CALENDAR_STATUS_NOT_SIGNEDUP,
		CALENDAR_STATUS_TENTATIVE,
		NUM_CALENDAR_STATUS
	}
}
