using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_WEB_ACTION_TYPE
	{
		CALENDAR_WEB_ACTION_TYPE_ACCEPT,
		CALENDAR_WEB_ACTION_TYPE_DECLINE,
		CALENDAR_WEB_ACTION_TYPE_REMOVE,
		CALENDAR_WEB_ACTION_TYPE_REPORT_SPAM,
		CALENDAR_WEB_ACTION_TYPE_SIGNUP,
		CALENDAR_WEB_ACTION_TYPE_TENTATIVE,
		CALENDAR_WEB_ACTION_TYPE_TENTATIVE_SIGNUP,
		NUM_CALENDAR_WEB_ACTION_TYPES
	}
}
