using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_INVITE_BITS
	{
		CALENDAR_INVITE_BIT_PENDING_INVITE = 1,
		CALENDAR_INVITE_BIT_MODERATOR,
		CALENDAR_INVITE_BIT_CREATOR = 4,
		CALENDAR_INVITE_BIT_SIGNUP = 8
	}
}
