using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_INVITE_SORT_TYPE
	{
		CALENDAR_INVITE_SORT_NAME,
		CALENDAR_INVITE_SORT_LEVEL,
		CALENDAR_INVITE_SORT_CLASS,
		CALENDAR_INVITE_SORT_STATUS,
		CALENDAR_INVITE_SORT_PARTY,
		CALENDAR_INVITE_SORT_NOTES,
		NUM_CALENDAR_INVITE_SORT_TYPES,
		DEFAULT_CALENDAR_INVITE_SORT_TYPE = 3
	}
}
