using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_GET_EVENT_TYPE
	{
		CALENDAR_GET_EVENT_TYPE_GET,
		CALENDAR_GET_EVENT_TYPE_ADD,
		CALENDAR_GET_EVENT_TYPE_COPY,
		DEFAULT_CALENDAR_GET_EVENT_TYPE = 0
	}
}
