using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_FILTER_FLAGS
	{
		CALENDAR_FILTER_FLAGS_WEEKLY_HOLIDAY = 1,
		CALENDAR_FILTER_FLAGS_DARKMOON,
		CALENDAR_FILTER_FLAGS_BATTLEGROUND = 4,
		CALENDAR_FILTER_FLAGS_RAID_LOCKOUT = 8,
		CALENDAR_FILTER_FLAGS_RAID_RESET = 16
	}
}
