using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_COMMAND_TYPE
	{
		CALENDAR_COMMAND_CREATE,
		CALENDAR_COMMAND_INVITE,
		CALENDAR_COMMAND_RSVP,
		CALENDAR_COMMAND_REMOVE_INVITE,
		CALENDAR_COMMAND_REMOVE_EVENT,
		CALENDAR_COMMAND_STATUS,
		CALENDAR_COMMAND_MODERATOR_STATUS,
		CALENDAR_COMMAND_GET_CALENDAR,
		CALENDAR_COMMAND_GET_EVENT,
		CALENDAR_COMMAND_UPDATE_EVENT,
		CALENDAR_COMMAND_COMPLAIN,
		CALENDAR_COMMAND_NOTES
	}
}
