using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_TYPE
	{
		CALENDAR_TYPE_PLAYER,
		CALENDAR_TYPE_COMMUNITY,
		CALENDAR_TYPE_RAID_LOCKOUT,
		CALENDAR_TYPE_RAID_RESET_DEPRECATED,
		CALENDAR_TYPE_HOLIDAY,
		CALENDAR_TYPE_HOLIDAY_WEEKLY,
		CALENDAR_TYPE_HOLIDAY_DARKMOON,
		CALENDAR_TYPE_HOLIDAY_BATTLEGROUND,
		NUM_CALENDAR_TYPES
	}
}
