using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_EVENT_REPEAT_OPTIONS
	{
		CALENDAR_REPEAT_NEVER,
		CALENDAR_REPEAT_WEEKLY,
		CALENDAR_REPEAT_BIWEEKLY,
		CALENDAR_REPEAT_MONTHLY,
		NUM_CALENDAR_REPEAT
	}
}
