using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_EVENT_BITS
	{
		CALENDAR_EVENT_BIT_PLAYER = 1,
		CALENDAR_EVENT_BIT_GUILD_DEPRECATED,
		CALENDAR_EVENT_BIT_SYSTEM = 4,
		CALENDAR_EVENT_BIT_HOLIDAY = 8,
		CALENDAR_EVENT_BIT_LOCKED = 16,
		CALENDAR_EVENT_BIT_AUTO_APPROVE = 32,
		CALENDAR_EVENT_BIT_COMMUNITY_ANNOUNCEMENT = 64,
		CALENDAR_EVENT_BIT_RAID_LOCKOUT = 128,
		CALENDAR_EVENT_BIT_ARENA_DEPRECATED = 256,
		CALENDAR_EVENT_BIT_RAID_RESET_DEPRECATED = 512,
		CALENDAR_EVENT_BIT_COMMUNITY_SIGNUP = 1024,
		CALENDAR_EVENT_BIT_GUILD_SIGNUP = 2048,
		CALENDAR_EVENT_BITS_COMMUNITY_WIDE = 3136,
		CALENDAR_EVENT_BITS_PLAYER_CREATED = 3395,
		CALENDAR_EVENT_BITS_CANT_COMPLAIN = 3788
	}
}
