using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_MODERATOR_STATUS
	{
		CALENDAR_MODERATOR_NONE,
		CALENDAR_MODERATOR_MODERATOR,
		CALENDAR_MODERATOR_CREATOR,
		NUM_CALENDAR_MODERATOR_STATUS
	}
}
