using System;

namespace WoWCompanionApp
{
	public enum CALENDAR_EVENT_TYPE
	{
		CALENDAR_EVENT_TYPE_NONE = -1,
		CALENDAR_EVENT_TYPE_RAID,
		CALENDAR_EVENT_TYPE_DUNGEON,
		CALENDAR_EVENT_TYPE_PVP,
		CALENDAR_EVENT_TYPE_MEETING,
		CALENDAR_EVENT_TYPE_OTHER,
		CALENDAR_EVENT_TYPE_HEROIC_DUNGEON_DEPRECATED,
		NUM_CALENDAR_EVENT_TYPES
	}
}
