using System;

namespace WowStatConstants
{
	public enum GARR_ABILITY_ACTION
	{
		COUNTER_MECHANIC,
		SOLO_MISSION,
		MOD_SUCCESS_CHANCE,
		MOD_TRAVEL_TIME,
		MOD_XP,
		FRIENDLY_RACE,
		LONG_MISSION,
		SHORT_MISSION,
		MOD_CURRENCY,
		LONG_TRAVEL,
		SHORT_TRAVEL,
		MOD_BIAS,
		PROFESSION,
		MOD_BRONZE_LOOT_CHANCE,
		MOD_SILVER_LOOT_CHANCE,
		MOD_GOLD_LOOT_CHANCE,
		MOD_ALL_LOOT_CHANCE,
		MOD_MISSION_TIME,
		MENTORING,
		MOD_GOLD,
		PREVENT_DEATH,
		TREASURE_ON_MISSION_SUCCESS,
		FRIENDLY_CLASS,
		ADVANTAGE_MECHANIC,
		MOD_SUCCESS_PER_DURABILITY,
		MOD_SUCCESS_DURABILITY_IN_RANGE,
		FRIENDLY_FOLLOWER,
		KILL_TROOPS,
		MOD_DURABILITY_COST,
		MOD_BONUS_LOOT_CHANCE,
		MOD_XP_FLAT,
		MOD_ITEMLEVEL,
		MOD_STARTING_DURABILITY,
		UNIQUE_TROOPS,
		MOD_CLASSSPEC_LIMIT,
		TROOP_RESURRECTION,
		MOD_COST_BY_RACE,
		REWARD_ON_WORLD_QUEST_COMPLETE,
		MOD_SUCCESS_BY_MISSIONS_IN_PROGRESS,
		MOD_MISSION_COST
	}
}
