using System;

namespace JamLib
{
	public enum JAM_DESTINATION
	{
		JAM_DESTINATION_WORLD,
		JAM_DESTINATION_USER,
		JAM_DESTINATION_SPAWN_ZONE,
		JAM_DESTINATION_MAELSTROM,
		JAM_DESTINATION_SCRYE,
		JAM_DESTINATION_GLOBAL,
		JAM_DESTINATION_PROXY,
		JAM_DESTINATION_WEB,
		JAM_DESTINATION_CHAT,
		JAM_DESTINATION_PARTY,
		JAM_DESTINATION_ROUTER,
		JAM_DESTINATION_LFG,
		JAM_DESTINATION_USER_ROUTER,
		JAM_DESTINATION_GMSUPPORT,
		JAM_DESTINATION_JSON_CLIENT,
		JAM_DESTINATION_WOWCONTROLLER,
		JAM_DESTINATION_ACCOUNT,
		JAM_DESTINATION_PET_BATTLE,
		JAM_DESTINATION_MOBILE,
		JAM_DESTINATION_LOG,
		JAM_DESTINATION_ASSET_MANIFEST,
		JAM_DESTINATION_ASSET_QUERY,
		JAM_DESTINATION_CHARACTER,
		JAM_DESTINATION_SERVER_APP,
		JAM_DESTINATION_COMMERCE,
		JAM_DESTINATION_UTILITY,
		JAM_DESTINATION_SHARD_MANAGER,
		JAM_DESTINATION_PUBLISHER
	}
}
