using System;

namespace bgs.types
{
	public enum PartyListenerEventType
	{
		ERROR_RAISED,
		JOINED_PARTY,
		LEFT_PARTY,
		PRIVACY_CHANGED,
		MEMBER_JOINED,
		MEMBER_LEFT,
		MEMBER_ROLE_CHANGED,
		RECEIVED_INVITE_ADDED,
		RECEIVED_INVITE_REMOVED,
		PARTY_INVITE_SENT,
		PARTY_INVITE_REMOVED,
		INVITE_REQUEST_ADDED,
		INVITE_REQUEST_REMOVED,
		CHAT_MESSAGE_RECEIVED,
		PARTY_ATTRIBUTE_CHANGED,
		MEMBER_ATTRIBUTE_CHANGED,
		OPERATION_CALLBACK
	}
}
